name: Scheduled Python Script

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:
    inputs:
      hour:
        description: 'Hour (0-23, in UTC)'
        required: true
        default: '8'
      minute:
        description: 'Minute (0-59)'
        required: true
        default: '00'

jobs:
  check_time_and_run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Check if current time matches user-specified time
      id: check-time
      run: |
        CURRENT_HOUR=$(date +'%H')
        CURRENT_MINUTE=$(date +'%M')
        if [ "$CURRENT_HOUR" -eq "${{ github.event.inputs.hour }}" ] && [ "$CURRENT_MINUTE" -eq "${{ github.event.inputs.minute }}" ]; then
          echo "MATCH_TIME=true" >> $GITHUB_ENV
        fi

    - name: Run Python script if time matches
      if: env.MATCH_TIME == 'true'
      run: python start_run.py do this work
