name: IP_ADDRESS

on: [push, workflow_dispatch]

jobs:
  find-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Get public IP
        run: |
          echo "The public IP is $(curl -s https://ifconfig.me)"
