name: SBI_URL

on:
  schedule:
    - cron: '0 18 * * 1-5'  # Runs at 8:30 AM, Saturday
  workflow_dispatch:   # Allows manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python stock_data_library/sbi_url.py
        shell: /usr/bin/bash -e {0}
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.10.13/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib
