name: Scheduled Python Script

on:
  schedule:
    - cron: '2 16 * * *'  # Runs at 07:00 UTC, which is 16:00 JST
  workflow_dispatch:

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify your Python version

    - name: Install dependencies
      run: pip install requests

    - name: Run Python script
      run: python start_run.py do this work
