name: Scheduled Python Script

on:
  schedule:
    - cron: '35 8 * * 1-5'
    - cron: '40 8 * * 1-5'
    - cron: '45 8 * * 1-5'
    - cron: '50 8 * * 1-5'
    - cron: '55 8 * * 1-5'
    - cron: '0 9 * * 1-5'
    - cron: '5 9 * * 1-5'
    - cron: '10 9 * * 1-5'
    - cron: '15 9 * * 1-5'
    - cron: '20 9 * * 1-5'
    - cron: '25 9 * * 1-5'
    - cron: '30 9 * * 1-5'
    - cron: '35 9 * * 1-5'
    - cron: '40 9 * * 1-5'
    - cron: '45 9 * * 1-5'
    - cron: '50 9 * * 1-5'
    - cron: '55 9 * * 1-5'
    - cron: '0 10 * * 1-5'
    - cron: '5 10 * * 1-5'
    - cron: '10 10 * * 1-5'
    - cron: '15 10 * * 1-5'
    - cron: '20 10 * * 1-5'
    - cron: '25 10 * * 1-5'
    - cron: '30 10 * * 1-5'
    - cron: '35 10 * * 1-5'
    - cron: '40 10 * * 1-5'
    - cron: '45 10 * * 1-5'
    - cron: '50 10 * * 1-5'
    - cron: '55 10 * * 1-5'
    - cron: '0 11 * * 1-5'
    - cron: '5 11 * * 1-5'
    - cron: '10 11 * * 1-5'
    - cron: '15 11 * * 1-5'
    - cron: '20 11 * * 1-5'
    - cron: '25 11 * * 1-5'
    - cron: '30 11 * * 1-5'
    - cron: '35 11 * * 1-5'
    - cron: '40 11 * * 1-5'
    - cron: '45 11 * * 1-5'
    - cron: '50 11 * * 1-5'
    - cron: '55 11 * * 1-5'
    - cron: '0 12 * * 1-5'
    - cron: '5 12 * * 1-5'
    - cron: '10 12 * * 1-5'
    - cron: '15 12 * * 1-5'
  workflow_dispatch:
  
jobs:
  run_script:
    runs-on: macos-latest  # Now using macOS runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests
          pip install pandas
          pip install beautifulsoup4
          pip install google-auth
          pip install oauthlib
          pip install google-auth-oauthlib
          pip install google-auth-httplib2
          pip install google-api-python-client

      - name: Run Python script
        run: python gd_continue.py
        working-directory: ./stock_data_price_per_date
        shell: bash

      - name: Run Python script
        run: python stock_data_price_per_date.py
        working-directory: ./stock_data_price_per_date
        shell: bash  # Changed to bash for macOS compatibility
    
      - name: Run Python script
        run: python gu_continue.py
        working-directory: ./stock_data_price_per_date
        shell: bash 
