name: STOCK_DATA_PER_DATE_INITHIAL

on:
  schedule:
    - cron: '20 7 * * 1-5'  # Runs at 8:30 AM UTC, Monday to Friday
  workflow_dispatch:  # Allows manual triggering

jobs:
  run_script:
    runs-on: macos-latest  # Now using macOS runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests
          pip install pandas
          pip install beautifulsoup4
          pip install google-auth
          pip install oauthlib
          pip install google-auth-oauthlib
          pip install google-auth-httplib2
          pip install google-api-python-client

      - name: Run commander_stock_moniter.py.py
        run: python commander_stock_moniter.py.py
        working-directory: ./STOCK_MONITER
        shell: bash
