name: Scheduled Python Script

on:
  schedule:
    - cron: '30 8 * * 1-5'  # Runs at 8:30 AM, Monday to Friday
  workflow_dispatch:   # Allows manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests
        pip install beautifulsoup4
        pip install google-auth
        # Add other dependencies as needed

    - name: Run Python script
      run: python stock_data_price_per_date/stock_data_price_per_date.py
      shell: /usr/bin/bash -e {0}
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.10.13/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib
