name: STOCK_MONITER

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  run_script:
    runs-on: macos-latest  # Now using macOS runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run commander_stock_moniter.py
        run: python commander_stock_moniter.py
        working-directory: ./STOCK_MONITER
        shell: bash
