name: STOCK_MONITER

on:
  schedule:
    - cron: '20 7 * * 1-5'  # Runs at 8:30 AM UTC, Monday to Friday
  workflow_dispatch:  # Allows manual triggering

jobs:
  run_script:
    runs-on: macos-latest  # Now using macOS runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests
          pip install pandas
          pip install beautifulsoup4
          pip install oauthlib
          pip install Pillow

      - name: Run commander_stock_moniter.py
        run: python commander_stock_moniter.py
        working-directory: ./STOCK_MONITER
        shell: bash

      - name: Commit and Push result.html
        run: |
          git config --local user.email "1510306@junten.ed.jp
          git config --local user.name "Y1k1"
          git add result.html
          git commit -m "Add or update result.html" || echo "No changes to commit"
          git push
