name: STOCK_DATA_PER_DATE_SUB_2

on:
  schedule:
    - cron: '40-59/5 7 * * 1-5'
    - cron: '0-55/5 8 * * 1-5'
    - cron: '0-55/5 9 * * 1-5'
    - cron: '0-30/5 10 * * 1-5'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script gd_continue.py
        run: python gd_continue.py
        working-directory: ./stock_data_price_per_date
        shell: bash

      - name: Run Python script stock_data_price_per_date.py
        run: python stock_data_price_per_date.py
        working-directory: ./stock_data_price_per_date
        shell: bash

      - name: Run Python script gu_continue.py
        run: python gu_continue.py
        working-directory: ./stock_data_price_per_date
        shell: bash
