name: Scheduled Python Script

on:
  schedule:
    - cron: '35 8 * * 1-5' # Runs at 8:35 AM UTC, Monday to Friday
    - cron: '40 8 * * 1-5' # Runs at 8:40 AM UTC, Monday to Friday
    - cron: '45 8 * * 1-5' # Runs at 8:45 AM UTC, Monday to Friday
    - cron: '50 8 * * 1-5' # Runs at 8:50 AM UTC, Monday to Friday
    - cron: '55 8 * * 1-5' # Runs at 8:55 AM UTC, Monday to Friday
    - cron: '0 9 * * 1-5'  # Runs at 9:00 AM UTC, Monday to Friday
    - cron: '5 9 * * 1-5'  # Runs at 9:05 AM UTC, Monday to Friday
    - cron: '10 9 * * 1-5' # Runs at 9:10 AM UTC, Monday to Friday
    - cron: '15 9 * * 1-5' # Runs at 9:15 AM UTC, Monday to Friday
    - cron: '20 9 * * 1-5' # Runs at 9:20 AM UTC, Monday to Friday
    - cron: '25 9 * * 1-5' # Runs at 9:25 AM UTC, Monday to Friday
    - cron: '30 9 * * 1-5' # Runs at 9:30 AM UTC, Monday to Friday
    - cron: '35 9 * * 1-5' # Runs at 9:35 AM UTC, Monday to Friday
    - cron: '40 9 * * 1-5' # Runs at 9:40 AM UTC, Monday to Friday
    - cron: '45 9 * * 1-5' # Runs at 9:45 AM UTC, Monday to Friday
    - cron: '50 9 * * 1-5' # Runs at 9:50 AM UTC, Monday to Friday
    - cron: '55 9 * * 1-5' # Runs at 9:55 AM UTC, Monday to Friday
    - cron: '0 10 * * 1-5' # Runs at 10:00 AM UTC, Monday to Friday
    - cron: '5 10 * * 1-5' # Runs at 10:05 AM UTC, Monday to Friday
    - cron: '10 10 * * 1-5' # Runs at 10:10 AM UTC, Monday to Friday
    - cron: '15 10 * * 1-5' # Runs at 10:15 AM UTC, Monday to Friday
    - cron: '20 10 * * 1-5' # Runs at 10:20 AM UTC, Monday to Friday
    - cron: '25 10 * * 1-5' # Runs at 10:25 AM UTC, Monday to Friday
    - cron: '30 10 * * 1-5' # Runs at 10:30 AM UTC, Monday to Friday
  workflow_dispatch:
  
jobs:
  run_script:
    runs-on: macos-latest  # Now using macOS runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests
          pip install pandas
          pip install beautifulsoup4
          pip install google-auth
          pip install oauthlib
          pip install google-auth-oauthlib
          pip install google-auth-httplib2
          pip install google-api-python-client

      - name: Run Python script
        run: python gd_continue.py
        working-directory: ./stock_data_price_per_date
        shell: bash

      - name: Run Python script
        run: python stock_data_price_per_date.py
        working-directory: ./stock_data_price_per_date
        shell: bash  # Changed to bash for macOS compatibility
    
      - name: Run Python script
        run: python gu_continue.py
        working-directory: ./stock_data_price_per_date
        shell: bash 
