name: STOCK_DATA_PER_DATE_INITHIAL

on:
  schedule:
    - cron: '20 7 * * 1-5'  # Runs at 8:30 AM UTC, Monday to Friday
  workflow_dispatch:  # Allows manual triggering

jobs:
  run_script:
    runs-on: macos-latest  # Now using macOS runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run stock_data_price_per_date_gd.py
        run: python stock_data_price_per_date_gd.py
        working-directory: ./stock_data_price_per_date
        shell: bash

      - name: Run Python script
        run: python stock_data_price_per_date.py
        working-directory: ./stock_data_price_per_date
        shell: bash  # Changed to bash for macOS compatibility
    
      - name: Run stock_data_price_per_date_gu.py
        run: python stock_data_price_per_date_gu.py
        working-directory: ./stock_data_price_per_date
        shell: bash 
